### ISSUE TITLE
using run_discrimination.py

### ISSUE THREAD

**Issue by gjia25** [rowanz/grover#10]
I'm aiming to finetune Grover for fake news classification. I started by testing out the discrimination script with input_data=generation_examples/generator=mega~dataset=p0.94.jsonl, and init_checkpoint=models/large (downloaded checkpoint), but I got the following error:

ValueError: Shape of variable newslm/embeddings/LayerNorm_embed_norm/beta:0 ((768,)) doesn't match with shape of tensor newslm/embeddings/LayerNorm_embed_norm/beta ([1024]) from checkpoint reader.

I read in another post that checkpoints for discrimination actually haven't been released. In that case, should I leave init_checkpoint=None, and how do I do that without getting the message 'exiting because no checkpoint'?

**Comment by rowanz** [comment]
I think the error here is because you're trying to initialize parameters for the base model with the large model 😄
