### ISSUE TITLE
Running on GPU

### ISSUE THREAD

**Issue by serenaklm** [rowanz/grover#14]
Hi, I am trying to fine tune this model with 2 GPU cards. (I have set use_tpu = false) I noticed that the GPU’s memories are filled ups. However, the utilization of both GPUs is 0%. Also, the consoles are not logging any output from training. 

May I check if it’s possible to  train the model with GPU? How should I go about training with GPU? 

Lastly, does anyone have experience running this on GPU? How’s the speed performance like?

Thanks to everyone in advance! :)

**Comment by rowanz** [comment]
sorry for taking forever to get to this --- You can generate text with any sized model on GPU. it should be possible to finetune at least Grover-Base on GPU. However, I never needed to do that for my experiments so I'm not supporting that right now in this repo, sorry!

I'm not sure what's going on in your case though. I've also found that it's difficult to use multiple GPUs on tensorflow :(
