### ISSUE TITLE
run_discrimination

### ISSUE THREAD

**Issue by igormis** [rowanz/grover#17]
I have my dataset on fake news, but I have two concerns:

1. How the dataset should be structured, i.e. text and what is the label?
2. Can i use the model from https://colab.research.google.com/drive/1esbpDOorf7DQJV8GXWON24c-EQrSKOit#scrollTo=ip52YU9X5BwB 

- MODEL = "grover_mega_owt_fix"
- NUMBER=800000

as pretrained model?

**Comment by rowanz** [comment]
my data looks something like this: https://github.com/rowanz/grover/blob/master/realnews/realnews_tiny.jsonl

also nope, that model is GPT2 trained using a modified version of this repo (for whatever reason...) rather than Grover :)
