### ISSUE TITLE
Colab TPU - What GPU/Server specs do I need to get article at least 1 article per minute?

### ISSUE THREAD

**Issue by hypnoai** [rowanz/grover#18]
Hi,
It works fine on the Google Colab TPU. for article generation.
Except I found that for generating a single article took around 10 minutes?

I didn't try it using the list of articles in the sample, there was 10 or so there, I don't know if it would process them all at once so would be quicker than ten minutes per article.. but will try tonight.

What GPU/Server specs do I need to get article at least 1 article per minute? (sorry to ask).

**Comment by rowanz** [comment]
hi there,

i wasn't able to get generation to work on TPUs. I used GPUs for generation. i think something like a p100 gpu will work here 😄
