### ISSUE TITLE
 Tensorflow Autograph Error

### ISSUE THREAD

**Issue by realdiganta** [rowanz/grover#19]
When I run this part of the code:

tokens, probs = sample(
        news_config=news_config,
        initial_context=initial_context,
        eos_token=eos_token,
        ignore_ids=ignore_ids,
        p_for_topp=p_for_topp,
        do_topk=False)

I am getting an error:

WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fc506e23f60>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fc506e23f60>>: AssertionError: Bad argument number for Name: 3, expecting 4

**Comment by Mockapapella** [comment]
I'm getting the same error. Haven't found a way around it yet

**Comment by rowanz** [comment]
I think your tensorflow version is different from mine. could you give me the results of `pip freeze` ?

**Comment by realdiganta** [comment]
tensor2tensor==1.14.1
tensorboard==1.15.0
tensorboardcolab==0.0.22
tensorflow==1.15.0rc3
tensorflow-datasets==1.2.0
tensorflow-estimator==1.15.1
tensorflow-gan==1.0.0.dev0
tensorflow-hub==0.6.0
tensorflow-metadata==0.15.0
tensorflow-probability==0.7.0
tflearn==0.3.2

**Comment by rowanz** [comment]
yep, you need to use tensorflow 1.13 for this project. (see the `requirements.txt`)
