### ISSUE TITLE
title generation

### ISSUE THREAD

**Issue by gompa** [rowanz/grover#24]
when running the conditional sample and trying to generate a title i get the folowing error: 
`tensorflow.python.framework.errors_impl.InvalidArgumentError: assertion failed: [] [Condition x <= y did not hold element-wise:x (sample_sequence/newslm/embeddings/strided_slice:0) = ] [1089] [y (sample_sequence/newslm/embeddings/assert_less_equal_1/y:0) = ] [1024]
	 [[{{node sample_sequence/newslm/embeddings/assert_less_equal_1/Assert/Assert}}]]
	 [[{{node sample_sequence/while/Exit_3}}]]
`
so with my limited understanding of the code, it seems that the title tokens dont get fit to the max seqence size when generating a title

is this a correct observation ? and if so is there a fix available ?

**Comment by rowanz** [comment]
Hmm, I think the issue is that the context tokens weren't being truncated correctly. If you can pinpoint the issue (and it's with the repo) I'd be happy to accept a PR fixing it :)

**Comment by onikula** [comment]
Hi @rowanz , this is the same error I ran into and e-mailed you about. I run into the error when adding the `-target title` argument, like below:

`python3 sample/contextual_generate.py -model_config_fn lm/configs/base.json -model_ckpt models/base/model.ckpt -metadata_fn sample/april2019_set_mini.jsonl -target title -out_fn april2019_set_mini_out.jsonl`

One title is generated in the output file and this error message pops up:
```
tensorflow.python.framework.errors_impl.InvalidArgumentError: assertion failed: [] [Condition x <= y did not hold element-wise:x (sample_sequence/newslm/embeddings/strided_slice:0) = ] [1073] [y (sample_sequence/newslm/embeddings/assert_less_equal_1/y:0) = ] [1024]
	 [[{{node sample_sequence/newslm/embeddings/assert_less_equal_1/Assert/Assert}}]]
```
Has there been any advances with this issue yet?

**Comment by rowanz** [comment]
thanks @onikula for the reminder! this should fix it https://github.com/rowanz/grover/commit/f59a206a8722357c351eae9e937b9f7a53bfda61 - let me know if it doesn't 😄
