### ISSUE TITLE
Running Discrimination

### ISSUE THREAD

**Issue by JavariaHassan** [rowanz/grover#30]
Hi, I have noticed that there are no checkpoints available for the discriminator model. Does this mean I will need to train the model with a TPU pod? If so, how long will the training take approximately? I'm planning to use the TPU system on google colab which has the following specifications:
Num TPU Cores: 8
Num TPU Workers: 1
Num TPU Cores Per Worker: 8

**Comment by rowanz** [comment]
You might be able to train it without a TPU pod, but the batch size for large models like grover-mega might not be enough for the training to work well. Unfortunately, if your goal is to discriminate on custom data then there's no getting around training from the generator checkpoint 😄

**Comment by JavariaHassan** [comment]
Thank you for your reply. I don't plan to train it on custom data, but the data you have uploaded on this link: https://github.com/rowanz/grover/tree/master/generation_examples since you haven't uploaded checkpoints for the discriminator model. I am a bit confused; I only want to get the pre-trained discriminator model running. Do I need to train the model with the data from the link, or do I only need to finetune? Thank you.

**Comment by rowanz** [comment]
You would need to finetune only. If you’re training on the given samples
though, I’d be happy to just share the discrimination checkpoints directly
- pm or email me :)
