### ISSUE TITLE
Scraping - how long does it take?

### ISSUE THREAD

**Issue by akhileshgotmare** [rowanz/grover#32]
`https://github.com/rowanz/grover/tree/master/realnews`
Here you mention that downloading + deduplicating common crawl is done on AWS instances (15 machines, each with 72 cpus). Could you provide an estimate of the duration for each of the processes here take - `process_ccrawl.sh` and `dedupe_crawl.py` and `prepare_lm_data.sh`? 

Also maybe I'm missing something but does the `process_ccrawl.sh` just download common crawl or does it also filter out all the non-news content?

**Comment by rowanz** [comment]
The great majority of time is spent on downloading common crawl, not sure the exact breakdown though. Non-news content is filtered out immediately, but it still must be iterated over since the files contain a mix of news and non-news.

hope that helps 😄
