### ISSUE TITLE
randomness in predictions?

### ISSUE THREAD

**Issue by danyaljj** [rowanz/grover#4]
I am trying to estimate next-token probabilities, for a given context. And to my surprise, there is randomness in the scoring the next token.

To be specific, here are key details of my code: 
I am loading the model like this: 
```python 
model_ckpt = ... 
tf_config = tf.ConfigProto(allow_soft_placement=True)
with tf.Session(config=tf_config, graph=tf.Graph()) as sess:
    initial_context = tf.placeholder(tf.int32, [batch_size_per_chunk, None])
    next_index = tf.placeholder(tf.int32, [])
    prob = assign_author_likelihoods(news_config=news_config, initial_context=initial_context,
                                     next_index=next_index)

    saver = tf.train.Saver()
    saver.restore(sess, model_ckpt)
```

and then make predictions: 
```python
modified_context = ... 
next_index_val = ... 
x = sess.run([prob], feed_dict={initial_context: [modified_context] * batch_size_per_chunk, next_index: next_index_val})
```
where `prob` is defined as: 
```python
prob = get_next_token_likelihood(news_config=news_config, initial_context=initial_context, next_index=next_index)
```
and `get_next_token_likelihood` is defined as: 
```python
def get_next_token_likelihood(news_config: GroverConfig, initial_context, next_index):
    batch_size, _ = get_shape_list(initial_context, expected_rank=2)

    model = GroverModel(
        config=news_config,
        is_training=False,
        input_ids=initial_context,
        reuse=tf.AUTO_REUSE,
        scope='newslm',
        chop_off_last_token=False,
        # do_cache=True,
        # cache=cache,
    )
    # Extract the FINAL SEQ LENGTH
    batch_size_times_seq_length, vocab_size = get_shape_list(model.logits_flat, expected_rank=2)
    next_logits = tf.reshape(model.logits_flat, [batch_size, -1, vocab_size])[:, -1]
    return next_logits[0][next_index]
```

Any thoughts why `x` (the output of `Session.run()`) is oscillating, each time that I run this code?  

@rowanz @schmmd

**Comment by schmmd** [comment]
Sorry--this went to my personal email.  I have no idea ;-)

Did you figure it out?

**Comment by danyaljj** [comment]
Somehow it went away (not sure what we changed when refactoring.) I suspect that for some reason were not loading the model properly. It seems to works reasonably now. If anything, I will reopen. 
Thanks for the followup, Michael!

**Comment by RinaldoG** [comment]
@danyaljj ~ Hello, I was wondering if you happened to still have the code for estimating the next token? If so would I be able to get a hold of it?
