### ISSUE TITLE
Wrong results

### ISSUE THREAD

**Issue by sandeepbhutani304** [rowanz/grover#8]
Hi,
I tried grover on my twitter and most of time is classified tweet posted by machine. For example, I checked almost 10 tweets of this person and all were classified as machine, but he is a human - [https://twitter.com/fs0c131y](https://twitter.com/fs0c131y)  , Or check tweets of Jeff [JeffDean](https://twitter.com/JeffDean) - only 3 of top 15 tweets were classified as human posts  
Before we use it in our project can you please check and revert if it is wrong classification or actually the tweets are machine generated.

**Comment by rowanz** [comment]
hi Sandeep,

i think you might be a bit confused about how Grover works. Essentially the task involves classifying **news articles** as machine-written (e.g. by Grover or by another generator like GPT-2) or human-written. The online demo was never trained on tweets, so it won't do well on them. You could, however, finetune a model for tweet classification, but this might be more difficult it's much easier to generate convincing tweets than it is to generate entire news articles.
